### ISSUE TITLE
[Request] Support Pantheon Applications

### ISSUE THREAD

**Issue by btd1337** [etiennegnome/EQUILIBRIUM#1]
Hi @etiennegnome,

Firstly, congratulations on this great work. This theme is amazing!

I would like know if it's possible do you to add support to [Pantheon applications](https://appcenter.elementary.io/) that uses some specific elementary OS components datailed in [this stylesheet](https://github.com/elementary/stylesheet)?

Thanks in advance!

**Comment by etiennegnome** [comment]
Thank you for your comment.

Like for QT5/6, I won't work on an Elementary version : too many work to understand the stylesheet, and same answer : the maintenance of the GTK3 code takes time, and GTK4 is coming : work to port this theme will be long, very long, and factidious, mainly because GTK4 code is not stabilized, and we, GTK themers, don't have enough information to make the job done easily.

Unlike others, I'm alone to do the job in my free time.
