### ISSUE TITLE
Won't work with QT5 Applications using QT5CT

### ISSUE THREAD

**Issue by OssNass** [etiennegnome/EQUILIBRIUM#2]
Your theme works great with GTK applications, however when using it with QT5 application using QT5CT style it won't work
![Screenshot from 2021-03-21 23-22-12](https://user-images.githubusercontent.com/5196218/111921272-693bf380-8a9c-11eb-9c94-4f500918a491.png)
My OS setup is:
Pop!_OS 20.04 LTS 64-bit
GNOME 3.36.8
QT 5.12.8

**Comment by etiennegnome** [comment]
Thank you for your comment. Yes Equilibrium doesn't work on QT5/6.
I won't work on a QT5/6 version because I don't know how to theme on it, and mainly because the maintenance of the GTK3 code takes time, and GTK4 is coming : the work to port the theme will be long, very long, and factidious.
It seems the GTK4 code is not stabilized yet, and the guys at Gnome aren't posting any information on how to do themes.
You know, we, GTK themers, are considered as hackers ....

**Comment by OssNass** [comment]
Thanks bro.
